### ISSUE TITLE
tag e2cnn==0.1.9 ? 

### ISSUE THREAD

**Issue by FabianSchuetze** [pointW/equi_q_corl21#2]
Can it be that the most recent version of e2cnn is not compatible with equi_q_corl21 anymore? 

When I run the main script (with different algos) with the most recent version of e2cnn, I received the following error:

```Python
Traceback (most recent call last):
  File "main.py", line 257, in <module>
    train()
  File "main.py", line 96, in train
    agent = createAgent()
  File "../scripts/create_agent.py", line 89, in createAgent
    fcn = EquResUDFRegNOut(1, num_primitives, domain_shape=(1, diag_length, diag_length), patch_shape=patch_shape, N=equi_n, n_middle_channels=(16, 32, 64, 128), kernel_size=3, quotient=False, last_quotient=True, initialize=initialize).to(device)
  File "../networks/equivariant_models.py", line 777, in __init__
    kernel_size=kernel_size, padding=kernel_size//2)
  File "../networks/r2conv_df.py", line 100, in __init__
    recompute=False)
TypeError: __init__() missing 1 required positional argument: 'points'
```
I see that e2cnn isn't tagged in the requirements.txt file. Would such tagging make sense?

**Comment by pointW** [comment]
Hello,

Thank you so much for pointing this out. During implementation, I used e2cnn==0.1.5. I just tagged this in the requirement.txt, could you please try using e2cnn==0.1.5 and see if that fixes the issue?

**Comment by pointW** [comment]
Hi @FabianSchuetze, does fixing e2cnn==0.1.5 solve the issue?

**Comment by FabianSchuetze** [comment]
Thanks for your kind and quick reply! Using the version you indicated indeed solves the issue and I'm glad that it does.
